### ISSUE TITLE
Unable to open program

### ISSUE THREAD

**Issue by nkssnim** [Doublevil/Houhou-SRS#15]
When I try to run the program from the shortcut or from its install directory (Program Files (x86)), even as an admin, it shows up in task manager briefly and disappears after a few seconds. The window does not even show and there is no error message upon crashing.

This started occurring after I hard reset (holding the power button) my PC with Houhou SRS open.

**This is what I got from event viewer:**
Event ID 1000, Application Error
```
Faulting application name: Houhou SRS.exe, version: 1.2.0.0, time stamp: 0x551d64c0
Faulting module name: KERNELBASE.dll, version: 10.0.14393.479, time stamp: 0x582588e6
Exception code: 0xe0434352
Fault offset: 0x0000000000017788
Faulting process id: 0x20c8
Faulting application start time: 0x01d2969eb35d017f
Faulting application path: C:\Program Files (x86)\Houhou SRS\Houhou SRS.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: ee96c924-3760-440c-a166-f33c4ba52dbe
Faulting package full name: 
Faulting package-relative application ID: 
```

**and another error here:**
Event ID 1026, .NET Runtime
```
Application: Houhou SRS.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.OnConfigRemoved(System.Configuration.Internal.InternalConfigEventArgs)
   at System.Configuration.Internal.InternalConfigRoot.RemoveConfigImpl(System.String, System.Configuration.BaseConfigurationRecord)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(System.String, Boolean, Boolean, Boolean, Boolean, System.Object ByRef, System.Object ByRef)
   at System.Configuration.BaseConfigurationRecord.GetSection(System.String)
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.ClientSettingsStore.ReadSettings(System.String, Boolean)
   at System.Configuration.LocalFileSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at Kanji.Interface.Properties.Settings.get_ShouldUpgradeSettings()
   at Kanji.Interface.Program.InitializeUserSettings()
   at Kanji.Interface.Program.Run()
   at Kanji.Interface.Program.Main(System.String[])
```
**Installing Houhou SRS on my D drive and running it from there gives no problems and I can use the program as normal.**

Appreciate any help you can give, thanks

**Comment by Doublevil** [comment]
It appears that the application cannot read its configuration file. This is probably because it has been corrupted because of the hard reset.
Uninstalling and reinstalling Houhou should fix the issue.

**Comment by nkssnim** [comment]
Just uninstalling and reinstalling did not fix it, but I figured it out:

I had to delete the Doublevil folder in AppData\Local since it was still trying to read the corrupted user.config file from there, then reinstall.
